require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/IndentationStyle:
  EnforcedStyle: tabs

Layout/IndentationWidth:
  Width: 1
