version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 5

  api:
    tty: true
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: .
    env_file:
      - ./.env
    volumes:
      - .:/api
    ports:
      - '3001:3000'
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  api:
