version: '3'

tasks:
  up:
    cmds:
      - bundle install
      - docker compose up --build -d
      - echo "Up and running!"
      - |
          if [ -n "$(rails db:exists)" ]; then
            echo "Database already exists. Skipping creation."
          else
            bundle exec rails db:create
          fi
      - task: migrate

  down:
    cmds:
      - docker compose down

  stop:
    cmds:
      - docker compose stop

  start:
    cmds:
      - docker compose up --build -d

  teardown:
    cmds:
      - docker compose up --build -d
      - docker compose exec api bundle exec rails db:drop
      - docker compose down

  format:
    cmds:
      - bundle exec rubocop -A

  lint:
    cmds:
      - bundle exec rubocop

  migrate:
    cmds:
      - docker compose exec api bundle exec rails db:migrate db:seed
      - docker cp $(docker-compose ps -q api):app/db/schema.rb ./db/schema.rb
      - docker compose exec api bundle exec annotate
      - docker cp $(docker-compose ps -q api):app/app ./

  secrets-dev:
    cmds:
      - EDITOR='code --wait' bundle exec rails credentials:edit --environment development

  secrets-prod:
    cmds:
      - EDITOR='code --wait' bundle exec rails credentials:edit --environment production

  secrets-staging:
    cmds:
      - EDITOR='code --wait' bundle exec rails credentials:edit --environment staging

  secrets-test:
    cmds:
      - EDITOR='code --wait' bundle exec rails credentials:edit --environment test

  console:
    cmds:
      - docker compose exec api bundle exec rails console

  # Task with environment variables
  with_env:
    env:
      VAR1: "value1"
      VAR2: "value2"
    cmds:
      - 'echo "VAR1: $VAR1, VAR2: $VAR2"'

  # Task with conditions
  conditional:
    cmds:
      - echo "This will only run on Linux"
    preconditions:
      - GOOS=linux

  # Task with dynamic dependencies
  dynamic_deps:
    cmds:
      - echo "This has dynamic dependencies"
    deps:
      - echo_dependency

  echo_dependency:
    cmds:
      - echo "This is a dependency"

  echo_dependency2:
    cmds:
      - echo "This is another dependency"
