name: Branch Checks

on:
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Run RSpec Tests
      run: |
        bundle exec rspec

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Run RuboCop
      run: |
        bundle exec rubocop

  annotations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Check Annotations
      run: |
        annotations=$(bundle exec annotate --check)
        if [ -n "$annotations" ]; then
          echo "Annotations check failed. Run 'bundle exec annotate' locally to update annotations."
          echo "Annotations found:"
          echo "$annotations"
          exit 1
        else
          echo "Annotations check passed. No new annotations needed."
        fi
